import { cookies } from 'next/headers';
import { notFound } from 'next/navigation';
import { getShareLinkForToken } from '@/server/delivery';
import { verifyDeliveryAccessCookie, DELIVERY_ACCESS_COOKIE } from '@/server/public-delivery';
import { AppError } from '@/server/errors';
import { PasswordGate } from './PasswordGate';

const PREVIEW_MIME_TYPES = new Set(['application/pdf', 'image/jpeg', 'image/png', 'image/gif', 'image/webp']);
function formatBytes(value: bigint) { const n = Number(value); if (!Number.isFinite(n)) return '—'; if (n < 1024) return `${n} B`; if (n < 1024 * 1024) return `${(n / 1024).toFixed(1)} KB`; if (n < 1024 * 1024 * 1024) return `${(n / 1024 / 1024).toFixed(1)} MB`; return `${(n / 1024 / 1024 / 1024).toFixed(1)} GB`; }
function AccessError({ message }: { message: string }) { return <main className="flex min-h-screen items-center justify-center px-5 py-12"><div className="w-full max-w-md rounded-[12px] border border-[var(--border)] bg-[var(--surface)] p-7 text-center"><p className="text-sm font-medium text-[var(--muted)]">Bàn giao không khả dụng</p><h1 className="mt-2 text-2xl font-semibold tracking-tight">{message}</h1><p className="mt-3 text-sm leading-6 text-[var(--muted)]">Vui lòng liên hệ người gửi để nhận một link mới.</p></div></main>; }

export default async function DeliveryPage({ params }: { params: Promise<{ token: string }> }) {
  const { token } = await params; let link;
  try { link = await getShareLinkForToken(token); } catch (error) { if (error instanceof AppError && ['SHARE_LINK_EXPIRED', 'SHARE_LINK_REVOKED', 'SHARE_LINK_LIMIT_REACHED'].includes(error.code)) return <AccessError message={error.message}/>; notFound(); }
  if (!link) notFound();
  if (link.passwordHash) { const cookie = (await cookies()).get(DELIVERY_ACCESS_COOKIE)?.value; if (!verifyDeliveryAccessCookie(cookie, link.id)) return <PasswordGate token={token} />; }
  return <main className="min-h-screen bg-[var(--background)] px-5 py-10 text-[var(--foreground)] sm:px-8"><div className="mx-auto max-w-3xl"><header className="border-b border-[var(--border)] pb-7"><p className="text-sm font-semibold tracking-wide text-[var(--muted)]">CLIENT FILE DELIVERY</p><h1 className="mt-4 text-3xl font-semibold tracking-tight">{link.delivery.title}</h1>{link.delivery.description && <p className="mt-2 max-w-2xl text-sm leading-6 text-[var(--muted)]">{link.delivery.description}</p>}<div className="mt-5 flex flex-wrap gap-x-5 gap-y-2 text-sm text-[var(--muted)]"><span>{link.delivery.files.length} file</span>{link.expiresAt && <span>Hết hạn {link.expiresAt.toLocaleDateString('vi-VN')}</span>}{link.maxDownloads !== null && <span>Còn {Math.max(0, link.maxDownloads - link.downloadCount)} lượt tải</span>}</div></header><section className="py-7" aria-label="Danh sách file"><div className="divide-y divide-[var(--border)] rounded-[10px] border border-[var(--border)] bg-[var(--surface)]">{link.delivery.files.map(({ file }) => <div key={file.id} className="flex items-center gap-4 px-4 py-4 sm:px-5"><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{file.originalName}</p><p className="mt-1 text-xs text-[var(--muted)]">{file.mimeType || 'File'} · {formatBytes(file.size)}</p></div><div className="flex shrink-0 gap-2">{PREVIEW_MIME_TYPES.has(file.mimeType) && <a className="focus-ring inline-flex h-9 items-center rounded-[8px] border border-[var(--border)] px-3 text-sm font-medium hover:bg-[var(--surface-muted)]" target="_blank" rel="noreferrer" href={`/api/public/deliveries/${encodeURIComponent(token)}/files/${encodeURIComponent(file.id)}/preview`}>Xem</a>}<a className="focus-ring inline-flex h-9 items-center rounded-[8px] border border-[var(--border)] px-3 text-sm font-medium hover:bg-[var(--surface-muted)]" href={`/api/public/deliveries/${encodeURIComponent(token)}/files/${encodeURIComponent(file.id)}`}>Tải xuống</a></div></div>)}</div></section><footer className="border-t border-[var(--border)] pt-5 text-xs text-[var(--muted)]">Nếu bạn gặp vấn đề khi tải file, vui lòng liên hệ người gửi để nhận hỗ trợ.</footer></div></main>;
}
