'use client';

import { useState } from 'react';
import { Button } from '@/components/ui/button';

export function AccountForms({ initialName, initialCompany, initialPhone }: { initialName: string; initialCompany: string; initialPhone: string }) {
  const [name, setName] = useState(initialName); const [companyName, setCompanyName] = useState(initialCompany); const [phone, setPhone] = useState(initialPhone); const [message, setMessage] = useState(''); const [passwords, setPasswords] = useState({ currentPassword: '', newPassword: '', confirmPassword: '' }); const [busy, setBusy] = useState(false);
  const saveProfile = async () => { setBusy(true); setMessage(''); try { const response = await fetch('/api/portal/account', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name, companyName, phone }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload?.error?.message ?? 'Không thể cập nhật.'); setMessage('Đã cập nhật thông tin.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Không thể cập nhật.'); } finally { setBusy(false); } };
  const changePassword = async () => { setBusy(true); setMessage(''); try { const response = await fetch('/api/portal/account', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(passwords) }); const payload = await response.json(); if (!response.ok) throw new Error(payload?.error?.message ?? 'Không thể đổi mật khẩu.'); setPasswords({ currentPassword: '', newPassword: '', confirmPassword: '' }); setMessage('Mật khẩu đã được thay đổi.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Không thể đổi mật khẩu.'); } finally { setBusy(false); } };
  const field = (label: string, value: string, setValue: (value: string) => void, type = 'text') => <label className="block"><span className="text-sm font-medium">{label}</span><input type={type} value={value} onChange={(event) => setValue(event.target.value)} className="focus-ring mt-2 h-10 w-full rounded-[8px] border border-[var(--border)] bg-[var(--surface)] px-3 text-sm outline-none focus:border-[var(--ring)]" /></label>;
  return <div className="space-y-4"><section className="surface rounded-[10px] p-5"><h2 className="text-sm font-semibold">Thông tin cá nhân</h2><div className="mt-4 grid gap-4 sm:grid-cols-2">{field('Họ tên', name, setName)}{field('Công ty', companyName, setCompanyName)}{field('Số điện thoại', phone, setPhone)}</div><div className="mt-5 flex items-center justify-between gap-3"><p className="text-xs text-[var(--muted)]">{message}</p><Button onClick={saveProfile} disabled={busy}>Lưu thay đổi</Button></div></section><section className="surface rounded-[10px] p-5"><h2 className="text-sm font-semibold">Bảo mật</h2><p className="mt-1 text-xs text-[var(--muted)]">Mật khẩu được xử lý và lưu bằng Argon2id ở phía máy chủ.</p><div className="mt-4 grid gap-4 sm:grid-cols-3">{field('Mật khẩu hiện tại', passwords.currentPassword, (value) => setPasswords((p) => ({ ...p, currentPassword: value })), 'password')}{field('Mật khẩu mới', passwords.newPassword, (value) => setPasswords((p) => ({ ...p, newPassword: value })), 'password')}{field('Xác nhận mật khẩu mới', passwords.confirmPassword, (value) => setPasswords((p) => ({ ...p, confirmPassword: value })), 'password')}</div><div className="mt-5 flex justify-end"><Button variant="secondary" onClick={changePassword} disabled={busy}>Đổi mật khẩu</Button></div></section></div>;
}
