'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { Plus, Search, Users } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { SectionPage } from '@/components/layout/section-page';

type Status = 'INVITED' | 'ACTIVE' | 'SUSPENDED' | 'DISABLED';
type Customer = { id: string; name: string | null; email: string; status: Status; customerProfile?: { companyName: string | null } | null; _count: { projectsOwned: number; filesUploaded: number } };
const statusLabel: Record<Status, string> = { INVITED: 'Chờ kích hoạt', ACTIVE: 'Đang hoạt động', SUSPENDED: 'Tạm khóa', DISABLED: 'Đã vô hiệu hóa' };

export default function CustomersPage() {
  const [items, setItems] = useState<Customer[]>([]); const [q, setQ] = useState(''); const [status, setStatus] = useState<Status | ''>(''); const [loading, setLoading] = useState(true); const [form, setForm] = useState({ name: '', email: '', companyName: '' }); const [saving, setSaving] = useState(false); const [activationUrl, setActivationUrl] = useState('');
  const load = async () => { setLoading(true); const params = new URLSearchParams({ q }); if (status) params.set('status', status); const res = await fetch(`/api/customers?${params.toString()}`); const json = await res.json(); setItems(json.data?.items ?? []); setLoading(false); };
  useEffect(() => { let cancelled = false; const params = new URLSearchParams({ q }); if (status) params.set('status', status); fetch(`/api/customers?${params.toString()}`).then(r => r.json()).then(json => { if (!cancelled) { setItems(json.data?.items ?? []); setLoading(false); } }); return () => { cancelled = true; }; }, [q, status]);
  async function createCustomer() { setSaving(true); setActivationUrl(''); try { const response = await fetch('/api/customers', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); const body = await response.json(); if (!response.ok) { window.alert(body.error?.message ?? 'Không thể tạo khách hàng.'); return; } const invitation = await fetch(`/api/customers/${body.data.id}/invitation`, { method: 'POST' }); const invitationBody = await invitation.json(); if (invitation.ok) setActivationUrl(invitationBody.data.activationUrl); setForm({ name: '', email: '', companyName: '' }); await load(); } finally { setSaving(false); } }
  return <SectionPage title="Khách hàng" description="Quản lý tài khoản, quyền truy cập và các dự án được bàn giao." icon={Users}>
    <div className="space-y-5">
      <div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div className="flex w-full flex-col gap-2 sm:flex-row sm:max-w-2xl"><div className="relative w-full sm:max-w-sm"><Search className="absolute left-3 top-2.5 h-4 w-4 text-[var(--muted)]" /><Input value={q} onChange={event => setQ(event.target.value)} placeholder="Tìm khách hàng..." className="pl-9" /></div><select value={status} onChange={event => setStatus(event.target.value as Status | '')} className="h-10 rounded-[9px] border border-[var(--border)] bg-[var(--surface)] px-3 text-sm"><option value="">Tất cả trạng thái</option>{Object.entries(statusLabel).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div><Button onClick={() => document.getElementById('customer-form')?.scrollIntoView({ behavior: 'smooth' })}><Plus className="h-4 w-4" />Thêm khách hàng</Button></div>
      <div className="overflow-x-auto rounded-[8px] border border-[var(--border)]"><table className="w-full min-w-[780px] text-sm"><thead className="bg-[var(--surface-muted)] text-left text-[var(--muted)]"><tr><th className="px-4 py-3">Khách hàng</th><th className="px-4 py-3">Trạng thái</th><th className="px-4 py-3">Dự án</th><th className="px-4 py-3">File</th><th className="px-4 py-3">Công ty</th></tr></thead><tbody>{loading ? <tr><td colSpan={5} className="px-4 py-12 text-center text-[var(--muted)]">Đang tải...</td></tr> : items.length === 0 ? <tr><td colSpan={5} className="px-4 py-12 text-center text-[var(--muted)]">Không có khách hàng phù hợp.</td></tr> : items.map(customer => <tr key={customer.id} className="border-t border-[var(--border)]"><td className="px-4 py-3"><Link className="font-medium hover:underline" href={`/khach-hang/${customer.id}`}>{customer.name || 'Chưa đặt tên'}</Link><p className="mt-0.5 text-xs text-[var(--muted)]">{customer.email}</p></td><td className="px-4 py-3"><span className="rounded-full bg-[var(--surface-muted)] px-2.5 py-1 text-xs">● {statusLabel[customer.status]}</span></td><td className="px-4 py-3">{customer._count.projectsOwned}</td><td className="px-4 py-3">{customer._count.filesUploaded}</td><td className="px-4 py-3 text-[var(--muted)]">{customer.customerProfile?.companyName || '—'}</td></tr>)}</tbody></table></div>
      <div id="customer-form" className="surface rounded-[10px] p-5"><h2 className="font-semibold">Thêm khách hàng</h2><p className="mt-1 text-sm text-[var(--muted)]">Khách hàng sẽ nhận lời mời và tự đặt mật khẩu.</p><div className="mt-4 grid gap-3 sm:grid-cols-3"><Input placeholder="Họ và tên" value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} /><Input placeholder="Email" type="email" value={form.email} onChange={event => setForm({ ...form, email: event.target.value })} /><Input placeholder="Công ty" value={form.companyName} onChange={event => setForm({ ...form, companyName: event.target.value })} /></div><div className="mt-3 flex justify-end"><Button disabled={saving} onClick={createCustomer}>{saving ? 'Đang tạo...' : 'Tạo khách hàng'}</Button></div>{activationUrl && <div className="mt-4 rounded-[9px] border border-[var(--border)] bg-[var(--surface-muted)] p-4"><p className="text-sm font-medium">Lời mời đã được tạo</p><p className="mt-1 break-all text-xs text-[var(--muted)]">{activationUrl}</p><div className="mt-3 flex gap-2"><Button variant="secondary" onClick={() => void navigator.clipboard.writeText(activationUrl)}>Sao chép link</Button></div></div>}</div>
    </div>
  </SectionPage>;
}
