import { z } from 'zod';
import { projectRepository } from '@/server/repositories/project-repository';
import { requireActor, requireAdmin } from '@/server/require-auth';
import { canViewProject } from '@/server/permissions';
import { projectService } from '@/server/services/project-service';
import { errorResponse, AppError } from '@/server/errors';
const schema=z.object({customerId:z.string().min(1),name:z.string().trim().min(2).max(160),description:z.string().trim().max(4000).optional(),status:z.enum(['DRAFT','IN_PROGRESS','READY','ARCHIVED']).optional(),customerUploadEnabled:z.boolean().optional()});
export async function GET(request:Request){try{const actor=await requireActor();const url=new URL(request.url);const id=url.searchParams.get('id');if(id){if(!(await canViewProject(actor,id)))throw new AppError('FORBIDDEN','Bạn không có quyền truy cập dự án này.',403);const item=await projectRepository.findById(id);if(!item)throw new AppError('PROJECT_NOT_FOUND','Không tìm thấy dự án.',404);return Response.json({data:item,error:null});}if(actor.role==='CUSTOMER'){const items=await projectRepository.listByCustomer(actor.id);return Response.json({data:{items,total:items.length,page:1,pageSize:items.length},error:null});}const q=url.searchParams.get('q')?.trim()||undefined;const customerId=url.searchParams.get('customerId');const page=Math.max(1,Number(url.searchParams.get('page')||1));const take=Math.min(50,Math.max(1,Number(url.searchParams.get('pageSize')||20)));const [items,total]=await projectRepository.list({q,skip:(page-1)*take,take});return Response.json({data:{items:customerId?items.filter(p=>p.customerId===customerId):items,total,page,pageSize:take},error:null});}catch(error){return errorResponse(error);}}
export async function POST(request:Request){try{const actor=await requireAdmin();const parsed=schema.safeParse(await request.json());if(!parsed.success)throw new AppError('INVALID_FILE',parsed.error.issues[0]?.message??'Dữ liệu không hợp lệ.');const item=await projectService.create(actor,parsed.data);return Response.json({data:item,error:null},{status:201});}catch(error){return errorResponse(error);}}
