import { requireAdmin } from '@/server/require-auth';
import { folderRepository } from '@/server/repositories/folder-repository';
import { AppError, errorResponse } from '@/server/errors';
import { logActivity } from '@/server/activity';

function validName(value: unknown) { const v = String(value ?? '').trim(); if (!v || v.length > 180 || v === '.' || v === '..' || v.includes('/') || v.includes('\\')) throw new AppError('INVALID_FOLDER', 'Tên thư mục không hợp lệ.'); return v; }
export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) { try { const actor = await requireAdmin(); const { id } = await params; const folder = await folderRepository.findById(id); if (!folder) throw new AppError('FOLDER_NOT_FOUND', 'Không tìm thấy thư mục.', 404); const body = await request.json(); if (body.name !== undefined) { const item = await folderRepository.rename(id, validName(body.name)); await logActivity({ userId: actor.id, projectId: folder.projectId, action: 'FOLDER_RENAMED', metadata: { folderId: id, name: item.name } }); return Response.json({ data: item, error: null }); } if (body.parentId !== undefined) { const parentId = body.parentId ? String(body.parentId) : null; if (parentId) { const parent = await folderRepository.findById(parentId); if (!parent || parent.projectId !== folder.projectId || parent.id === id) throw new AppError('INVALID_FOLDER', 'Thư mục cha không hợp lệ.'); } const item = await folderRepository.move(id, parentId); await logActivity({ userId: actor.id, projectId: folder.projectId, action: 'FOLDER_MOVED', metadata: { folderId: id, parentId } }); return Response.json({ data: item, error: null }); } throw new AppError('INVALID_FOLDER', 'Không có thay đổi hợp lệ.'); } catch (error) { return errorResponse(error); } }

export async function DELETE(_request: Request, { params }: { params: Promise<{ id: string }> }) { try { const actor = await requireAdmin(); const { id } = await params; const folder = await folderRepository.findById(id); if (!folder) throw new AppError('FOLDER_NOT_FOUND', 'Không tìm thấy thư mục.', 404); if (folder._count.files || folder._count.children) throw new AppError('INVALID_FOLDER', 'Thư mục chưa trống. Hãy xóa hoặc di chuyển nội dung trước.'); await folderRepository.delete(id); await logActivity({ userId: actor.id, projectId: folder.projectId, action: 'FOLDER_DELETED', metadata: { folderId: id, name: folder.name } }); return Response.json({ data: { id }, error: null }); } catch (error) { return errorResponse(error); } }
