import Link from 'next/link';
import { ArrowLeft, Download, Package } from 'lucide-react';
import { prisma } from '@/lib/db/prisma';
import { requireAdmin } from '@/server/require-auth';
import { ShareLinkPanel } from './ShareLinkPanel';

export default async function DeliveryDetailPage({ params }: { params: Promise<{ id: string; deliveryId: string }> }) {
  await requireAdmin(); const { id, deliveryId } = await params;
  const delivery = await prisma.delivery.findUnique({ where: { id: deliveryId, projectId: id }, include: { project: { select: { id: true, name: true } }, files: { include: { file: { select: { id: true, originalName: true, mimeType: true, size: true } } } }, shareLinks: { orderBy: { createdAt: 'desc' }, select: { id: true, expiresAt: true, maxDownloads: true, downloadCount: true, isActive: true, lastAccessedAt: true, createdAt: true } } } });
  if (!delivery) return <div className="p-8 text-sm text-[var(--muted)]">Không tìm thấy bàn giao.</div>;
  return <div className="space-y-6"><div><Link href={`/du-an/${id}/ban-giao`} className="inline-flex items-center gap-2 text-sm text-[var(--muted)] hover:text-[var(--foreground)]"><ArrowLeft className="h-4 w-4"/>Bàn giao</Link><div className="mt-4 flex items-start justify-between gap-4"><div><p className="text-sm text-[var(--muted)]">{delivery.project.name}</p><h1 className="mt-1 text-2xl font-semibold tracking-tight">{delivery.title}</h1>{delivery.description && <p className="mt-2 max-w-2xl text-sm text-[var(--muted)]">{delivery.description}</p>}</div><Package className="h-6 w-6 text-[var(--muted)]"/></div></div><div className="grid gap-3 sm:grid-cols-4"><div className="surface rounded-[10px] p-4"><p className="text-xs text-[var(--muted)]">Trạng thái</p><p className="mt-1 font-semibold">{delivery.status}</p></div><div className="surface rounded-[10px] p-4"><p className="text-xs text-[var(--muted)]">Số file</p><p className="mt-1 font-semibold">{delivery.files.length}</p></div><div className="surface rounded-[10px] p-4"><p className="text-xs text-[var(--muted)]">Link</p><p className="mt-1 font-semibold">{delivery.shareLinks.length}</p></div><div className="surface rounded-[10px] p-4"><p className="text-xs text-[var(--muted)]">Lượt tải</p><p className="mt-1 font-semibold">{delivery.shareLinks.reduce((sum, link) => sum + link.downloadCount, 0)}</p></div></div><section className="surface rounded-[10px] p-5"><h2 className="font-semibold">File bàn giao</h2><div className="mt-4 divide-y divide-[var(--border)]">{delivery.files.map(({ file }) => <div key={file.id} className="flex items-center gap-4 py-3"><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{file.originalName}</p><p className="mt-1 text-xs text-[var(--muted)]">{file.mimeType} · {(Number(file.size) / 1024 / 1024).toFixed(1)} MB</p></div><a className="inline-flex h-9 items-center gap-2 rounded-[8px] border border-[var(--border)] px-3 text-sm hover:bg-[var(--surface-muted)]" href={`/api/files/${file.id}`}><Download className="h-4 w-4"/>Tải xuống</a></div>)}{delivery.files.length===0 && <p className="py-8 text-center text-sm text-[var(--muted)]">Không có file.</p>}</div></section><ShareLinkPanel deliveryId={delivery.id} initialLinks={delivery.shareLinks.map((link) => ({ ...link, expiresAt: link.expiresAt?.toISOString() ?? null, lastAccessedAt: link.lastAccessedAt?.toISOString() ?? null, createdAt: link.createdAt.toISOString() }))}/></div>;
}
