import Link from 'next/link';
import { notFound } from 'next/navigation';
import { Activity, ArrowLeft, Download, FileText, PackageCheck } from 'lucide-react';
import { auth } from '../../../../../auth';
import { prisma } from '@/lib/db/prisma';
import { Badge } from '@/components/ui/badge';
import { CustomerUpload } from '@/components/portal/customer-upload';

const labels: Record<string, string> = { DRAFT: 'Bản nháp', IN_PROGRESS: 'Đang thực hiện', READY: 'Sẵn sàng', ARCHIVED: 'Đã lưu trữ' };
const activityLabels: Record<string, string> = { DELIVERY_CREATED: 'Bàn giao mới được tạo', CUSTOMER_OPENED_DELIVERY: 'Bạn đã mở bàn giao', CUSTOMER_FILE_UPLOADED: 'Bạn đã gửi tài liệu', FILE_UPLOADED: 'Có file mới được thêm', FILE_DOWNLOADED: 'File đã được tải xuống', PROJECT_UPDATED: 'Dự án đã được cập nhật' };

export default async function PortalProjectPage({ params }: { params: Promise<{ id: string }> }) {
  const session = await auth(); const { id } = await params;
  const project = await prisma.project.findFirst({ where: { id, customerId: session!.user.id }, include: { files: { orderBy: { createdAt: 'desc' }, take: 50 }, deliveries: { include: { _count: { select: { files: true } } }, orderBy: { createdAt: 'desc' }, take: 20 }, activities: { where: { action: { in: ['DELIVERY_CREATED', 'CUSTOMER_OPENED_DELIVERY', 'CUSTOMER_FILE_UPLOADED', 'FILE_UPLOADED', 'FILE_DOWNLOADED', 'PROJECT_UPDATED'] } }, orderBy: { createdAt: 'desc' }, take: 12 } } });
  if (!project) notFound();
  const totalBytes = project.files.reduce((sum, file) => sum + Number(file.size), 0);
  return <div className="space-y-6"><Link href="/portal/projects" className="focus-ring inline-flex items-center gap-2 text-xs text-[var(--muted)] hover:text-[var(--foreground)]"><ArrowLeft className="h-3.5 w-3.5" />Tất cả dự án</Link><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h1 className="text-2xl font-semibold tracking-tight">{project.name}</h1><Badge variant="outline">{labels[project.status]}</Badge></div>{project.description ? <p className="mt-2 max-w-2xl text-sm leading-6 text-[var(--muted)]">{project.description}</p> : null}</div><div className="flex gap-4 text-xs text-[var(--muted)]"><span>{project.files.length} file</span><span>{project.deliveries.length} bàn giao</span><span>{formatBytes(totalBytes)}</span></div></header>
    <div className="grid gap-4 lg:grid-cols-[1.15fr_0.85fr]">
      <section className="surface rounded-[10px]"><div className="flex items-center justify-between border-b border-[var(--border)] px-5 py-4"><div><h2 className="text-sm font-semibold">File</h2><p className="mt-1 text-xs text-[var(--muted)]">Các file thuộc dự án này.</p></div></div>{project.files.length ? <div className="divide-y divide-[var(--border)]">{project.files.map((file) => <div key={file.id} className="flex min-w-0 items-center gap-3 px-5 py-3"><div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-[7px] bg-[var(--surface-muted)]"><FileText className="h-4 w-4 text-[var(--muted)]" /></div><div className="min-w-0 flex-1"><p className="truncate text-sm">{file.originalName}</p><p className="mt-1 text-[11px] text-[var(--muted)]">{formatBytes(Number(file.size))}</p></div><a href={`/api/files/${file.id}`} className="focus-ring rounded-[7px] p-2 text-[var(--muted)] hover:bg-[var(--surface-muted)] hover:text-[var(--foreground)]" aria-label={`Tải ${file.originalName}`}><Download className="h-4 w-4" /></a></div>)}</div> : <div className="px-5 py-12 text-center text-sm text-[var(--muted)]">Chưa có file nào.</div>}</section>
      <section className="surface rounded-[10px]"><div className="border-b border-[var(--border)] px-5 py-4"><h2 className="text-sm font-semibold">Bàn giao</h2><p className="mt-1 text-xs text-[var(--muted)]">Các bộ file đã được gửi cho bạn.</p></div>{project.deliveries.length ? <div className="divide-y divide-[var(--border)]">{project.deliveries.map((delivery) => <Link key={delivery.id} href={`/portal/deliveries/${delivery.id}`} className="focus-ring flex items-center gap-3 px-5 py-4 hover:bg-[var(--surface-muted)]"><div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-[7px] bg-[var(--surface-muted)] text-[var(--primary)]"><PackageCheck className="h-4 w-4" /></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{delivery.title}</p><p className="mt-1 text-xs text-[var(--muted)]">{delivery._count.files} file</p></div></Link>)}</div> : <div className="px-5 py-12 text-center text-sm text-[var(--muted)]">Chưa có bàn giao nào.</div>}</section>
    </div>
    <section className="surface rounded-[10px]"><div className="flex items-center gap-3 border-b border-[var(--border)] px-5 py-4"><Activity className="h-4 w-4 text-[var(--muted)]" /><div><h2 className="text-sm font-semibold">Hoạt động</h2><p className="mt-1 text-xs text-[var(--muted)]">Những cập nhật liên quan đến dự án của bạn.</p></div></div>{project.activities.length ? <div className="divide-y divide-[var(--border)]">{project.activities.map((item) => <div key={item.id} className="flex items-start gap-3 px-5 py-3"><span className="mt-1.5 h-2 w-2 shrink-0 rounded-full bg-[var(--primary)]" /><div className="min-w-0 flex-1"><p className="text-sm">{activityLabels[item.action] ?? 'Dự án có cập nhật mới'}</p><p className="mt-1 text-[11px] text-[var(--muted)]">{formatRelative(item.createdAt)}</p></div></div>)}</div> : <div className="px-5 py-10 text-center text-sm text-[var(--muted)]">Chưa có hoạt động nào.</div>}</section>
    {project.customerUploadEnabled ? <CustomerUpload projectId={project.id} /> : <div className="surface rounded-[10px] p-5 text-sm text-[var(--muted)]">Đội ngũ chưa bật quyền gửi tài liệu cho dự án này.</div>}
  </div>;
}
function formatBytes(bytes: number) { if (bytes < 1024) return `${bytes} B`; const units = ['KB', 'MB', 'GB']; let value = bytes / 1024; for (const unit of units) { if (value < 1024) return `${value.toFixed(value >= 10 ? 0 : 1)} ${unit}`; value /= 1024; } return `${value.toFixed(1)} TB`; }
function formatRelative(date: Date) { const minutes = Math.floor((Date.now() - date.getTime()) / 60000); if (minutes < 1) return 'Vừa xong'; if (minutes < 60) return `${minutes} phút trước`; const hours = Math.floor(minutes / 60); if (hours < 24) return `${hours} giờ trước`; return `${Math.floor(hours / 24)} ngày trước`; }
