import Link from 'next/link';
import { Bell, ChevronRight, LockKeyhole, Palette, Settings, UserRound } from 'lucide-react';
import { auth } from '../../../../auth';
import { ThemeSettings } from '@/components/layout/theme-settings';

export default async function SettingsPage() {
  const session = await auth();
  return <div className="space-y-7"><header><p className="text-xs font-semibold uppercase tracking-[.14em] text-[var(--primary)]">Hệ thống</p><h1 className="mt-2 text-2xl font-semibold tracking-tight sm:text-[30px]">Cài đặt</h1><p className="mt-2 text-sm leading-6 text-[var(--muted)]">Quản lý tài khoản, giao diện và các tùy chọn workspace.</p></header><div className="grid gap-4 lg:grid-cols-[1.2fr_.8fr]"><section className="surface overflow-hidden rounded-[14px]"><div className="border-b border-[var(--border)] px-5 py-4"><h2 className="text-sm font-semibold">Tài khoản</h2><p className="mt-1 text-xs text-[var(--muted)]">Thông tin đang dùng để đăng nhập.</p></div><div className="divide-y divide-[var(--border)]"><div className="flex items-center gap-4 px-5 py-4"><div className="flex h-10 w-10 items-center justify-center rounded-full bg-[var(--primary-soft)] text-[var(--primary)]"><UserRound className="h-4 w-4" /></div><div className="min-w-0"><p className="text-sm font-medium">{session?.user.name ?? 'Tài khoản'}</p><p className="mt-1 truncate text-xs text-[var(--muted)]">{session?.user.email}</p></div></div><Link href="/portal/account" className="flex items-center gap-4 px-5 py-4 hover:bg-[var(--surface-muted)]"><LockKeyhole className="h-4 w-4 text-[var(--muted)]" /><div className="flex-1"><p className="text-sm font-medium">Bảo mật & tài khoản</p><p className="mt-1 text-xs text-[var(--muted)]">Xem thông tin tài khoản và các tùy chọn bảo mật.</p></div><ChevronRight className="h-4 w-4 text-[var(--muted)]" /></Link><div className="flex items-center gap-4 px-5 py-4"><Bell className="h-4 w-4 text-[var(--muted)]" /><div className="flex-1"><p className="text-sm font-medium">Thông báo</p><p className="mt-1 text-xs text-[var(--muted)]">Xem và xử lý các thông báo mới nhất.</p></div><Link href="/thong-bao" className="text-xs font-semibold text-[var(--primary)]">Mở</Link></div></div></section><section className="surface rounded-[14px] p-5"><div className="flex items-start gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-[var(--primary-soft)] text-[var(--primary)]"><Palette className="h-4 w-4" /></div><div><h2 className="text-sm font-semibold">Giao diện</h2><p className="mt-1 text-xs leading-5 text-[var(--muted)]">Chọn sáng, tối hoặc theo hệ thống.</p></div></div><ThemeSettings /><div className="mt-6 rounded-xl bg-[var(--surface-muted)] p-4"><div className="flex items-center gap-2 text-xs font-medium"><Settings className="h-3.5 w-3.5" /> Workspace</div><p className="mt-2 text-xs leading-5 text-[var(--muted)]">Các cài đặt nâng cao sẽ được mở rộng tại đây khi có thêm module quản trị.</p></div></section></div></div>;
}
