import Link from 'next/link';
import { Bell, ChevronRight, LockKeyhole, Palette, UserRound } from 'lucide-react';
import { auth } from '../../../../auth';
import { ThemeSettings } from '@/components/layout/theme-settings';

export default async function SettingsPage() {
  const session = await auth();
  return <div className="space-y-8 ui-rise">
    <header className="border-b border-[var(--border)] pb-6"><p className="text-[11px] font-bold uppercase tracking-[.17em] text-[var(--primary)]">Workspace / Cài đặt</p><div className="mt-2 flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-3xl font-semibold tracking-[-.035em]">Cài đặt</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[var(--muted)]">Quản lý tài khoản quản trị, giao diện và các thiết lập hiện có trong workspace.</p></div><span className="border border-[var(--border)] bg-[var(--surface-warm)] px-3 py-1.5 text-[10px] font-bold uppercase tracking-[.13em] text-[var(--accent)]">Quản trị</span></div></header>
    <div className="grid gap-5 lg:grid-cols-[1.25fr_.75fr]">
      <section className="surface overflow-hidden rounded-[12px]"><div className="border-b border-[var(--border)] bg-[var(--surface-muted)] px-5 py-4"><h2 className="text-sm font-bold">Tài khoản quản trị</h2><p className="mt-1 text-xs text-[var(--muted)]">Thông tin dùng cho tài khoản đang đăng nhập và bảo mật phiên.</p></div><div className="divide-y divide-[var(--border)]">
        <div className="flex items-center gap-4 px-5 py-5"><div className="flex h-11 w-11 items-center justify-center rounded-full bg-[var(--primary-soft)] text-sm font-bold text-[var(--primary)]">{(session?.user.name ?? 'Q').slice(0,1).toUpperCase()}</div><div className="min-w-0"><p className="text-sm font-bold">{session?.user.name ?? 'Quản trị viên'}</p><p className="mt-1 truncate text-xs text-[var(--muted)]">{session?.user.email}</p></div></div>
        <Link href="/tai-khoan" className="group flex items-center gap-4 px-5 py-5 transition-colors hover:bg-[var(--surface-muted)]"><span className="flex h-9 w-9 items-center justify-center rounded-[7px] bg-[var(--surface-sage)] text-[var(--primary)]"><LockKeyhole className="h-4 w-4" /></span><div className="flex-1"><p className="text-sm font-semibold">Tài khoản & bảo mật</p><p className="mt-1 text-xs text-[var(--muted)]">Đổi thông tin cá nhân, mật khẩu và thu hồi các phiên đăng nhập.</p></div><ChevronRight className="h-4 w-4 text-[var(--muted)] transition-transform group-hover:translate-x-1" /></Link>
        <Link href="/thong-bao" className="group flex items-center gap-4 px-5 py-5 transition-colors hover:bg-[var(--surface-muted)]"><span className="flex h-9 w-9 items-center justify-center rounded-[7px] bg-[var(--surface-sky)] text-[var(--info)]"><Bell className="h-4 w-4" /></span><div className="flex-1"><p className="text-sm font-semibold">Thông báo</p><p className="mt-1 text-xs text-[var(--muted)]">Mở inbox thông báo và xử lý các cập nhật mới nhất.</p></div><span className="text-xs font-bold text-[var(--primary)]">Mở</span></Link>
      </div></section>
      <section className="surface rounded-[12px] p-5"><div className="flex items-start gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-[7px] bg-[var(--surface-warm)] text-[var(--accent)]"><Palette className="h-4 w-4" /></div><div><h2 className="text-sm font-bold">Giao diện</h2><p className="mt-1 text-xs leading-5 text-[var(--muted)]">Ưu tiên giao diện sáng, hoặc đồng bộ theo thiết bị khi cần.</p></div></div><ThemeSettings /><div className="mt-7 border-t border-[var(--border)] pt-5"><div className="flex items-center gap-2 text-xs font-bold"><UserRound className="h-3.5 w-3.5 text-[var(--muted)]" />Phiên hiện tại</div><p className="mt-2 text-xs leading-5 text-[var(--muted)]">Các thao tác bảo mật được quản lý trong trang tài khoản để tránh trộn với tùy chọn hiển thị.</p></div></section>
    </div>
  </div>;
}
