'use client';

import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';

type FileItem = { id: string; originalName: string; mimeType: string; size: string };

export function DeliveryCreator({ projectId, files }: { projectId: string; files: FileItem[] }) {
  const [title, setTitle] = useState(''); const [description, setDescription] = useState(''); const [selected, setSelected] = useState<string[]>([]); const [expires, setExpires] = useState(''); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  function toggle(id: string) { setSelected((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]); }
  async function submit() { setBusy(true); setMessage(''); const response = await fetch('/api/deliveries', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ projectId, title, description: description || null, expiresAt: expires ? new Date(expires).toISOString() : null, fileIds: selected }) }); const json = await response.json(); setBusy(false); if (!response.ok) { setMessage(json.error?.message ?? 'Không thể tạo bàn giao.'); return; } window.location.href = `/du-an/${projectId}/ban-giao/${json.data.id}`; }
  return <section className="surface rounded-[10px] p-5"><div><h2 className="font-semibold">Tạo bàn giao</h2><p className="mt-1 text-sm text-[var(--muted)]">Chọn file hiện có trong dự án. File gốc không bị sao chép.</p></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><Input placeholder="Tên bàn giao" value={title} onChange={(event) => setTitle(event.target.value)}/><Input type="datetime-local" value={expires} onChange={(event) => setExpires(event.target.value)}/><Input className="sm:col-span-2" placeholder="Mô tả" value={description} onChange={(event) => setDescription(event.target.value)}/></div><div className="mt-5 divide-y divide-[var(--border)] rounded-[8px] border border-[var(--border)]">{files.map((file) => <label key={file.id} className="flex cursor-pointer items-center gap-3 px-4 py-3 hover:bg-[var(--surface-muted)]"><input type="checkbox" checked={selected.includes(file.id)} onChange={() => toggle(file.id)}/><span className="min-w-0 flex-1 truncate text-sm font-medium">{file.originalName}</span><span className="text-xs text-[var(--muted)]">{file.mimeType} · {(Number(file.size) / 1024 / 1024).toFixed(1)} MB</span></label>)}{files.length === 0 && <p className="px-4 py-8 text-center text-sm text-[var(--muted)]">Dự án chưa có file.</p>}</div><div className="mt-4 flex items-center justify-between gap-4"><span className="text-sm text-[var(--muted)]">{selected.length} file đã chọn</span><div className="flex items-center gap-3"><span aria-live="polite" className="text-sm text-[var(--destructive)]">{message}</span><Button disabled={busy || !title.trim() || !selected.length} onClick={submit}>{busy ? 'Đang tạo...' : 'Tạo bàn giao'}</Button></div></div></section>;
}
